INSERT INTO tl_cds_cad_individual (
    co_tipo_revisao, nu_cns_cidadao, nu_micro_area, nu_cpf_cidadao,
    nu_cpf_responsavel, dt_cad_individual, dt_entrada_brasil, dt_nascimento,
    dt_nascimento_responsavel, dt_naturalizacao, dt_obito, st_desconhece_nome_mae,
    st_desconhece_nome_pai, ds_email_cidadao, st_atualizacao, no_cidadao,
    no_cidadao_filtro, no_mae_cidadao, no_pai_cidadao, no_social_cidadao,
    nu_cartao_sus_responsavel, nu_pis_pasep, nu_celular_cidadao, nu_declaracao_obito,
    ds_portaria_naturalizacao, ds_rg_recusa_cad, co_sexo, st_ficha, st_versao_atual,
    st_erro_inativacao, st_fora_area, st_gerado_automaticamente, st_ficha_inativa,
    st_recusa_cad, st_responsavel_familiar, tp_cds_origem, co_unico_ficha,
    co_unico_grupo, co_unico_ficha_origem, ds_versao_ficha, co_cbo, co_etnia,
    co_localidade_origem, co_municipio, co_nacionalidade, co_pais,
    co_cds_prof_cadastrante, co_raca_cor, co_unidade_saude, co_seq_cds_cad_individual,
    co_revisao
) VALUES (
    '0',
    'ead30cc11711fb410fb10e74ad79a5d1',
    '01',
    NULL,
    NULL,
    '2025-09-12 12:00:00',
    NULL,
    '2008-03-08 12:00:00',
    NULL,
    NULL,
    NULL,
    '0',
    '0',
    NULL,
    '0',
    'VITORIA MARIA NOGUEIRA SENA',
    ' vitoria maria nogueira sena',
    'FRANCISCA VALCIONEIDE ALVES NOGUEIRA',
    'ROBSON HOLANDA LOPES SENA',
    '',
    NULL,
    NULL,
    '88936685452',
    NULL,
    NULL,
    NULL,
    '1',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    NULL,
    '1',
    '9017364-31ba4fb1-9fe3-4cb7-9585-891fdd6721ee',
    '50395e60-73f5-4da5-b7e9-63db1961cf19',
    '9017364-31ba4fb1-9fe3-4cb7-9585-891fdd6721ee',
    '7.2.3',
    NULL,
    NULL,
    '1407',
    '1531',
    '1',
    '31',
    '1',
    '4',
    NULL,
    '2',
    '5'
);
